[server]
host: 0.0.0.0
port: 7125
klippy_uds_address: /opt/printer_data/run/klippy.sock

[authorization]
cors_domains:
    *

trusted_clients:
    127.0.0.1
    10.0.0.0/8
    172.16.0.0/12
    192.168.0.0/16
    100.64.0.0/10    # <-- Pastikan subnet IP 100.64.x.x Anda tercantum di sini
    # Atau tambahkan IP spesifik host/browser Anda, misal:
    # 100.64.0.3

[octoprint_compat]

[file_manager]
queue_gcode_uploads: True
enable_object_processing: False
gcode_path: /opt/printer_data/gcodes

[data_store]
logger_path: /opt/printer_data/logs